<a href="https://colab.research.google.com/github/0rukpa/EDA_on_messy_datasets/blob/main/FIFA_DATASET_CLEANING_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#uploading my csv file
df = pd.read_csv('/titanic.csv')

print('Source file successfully uploaded')

Source file successfully uploaded

In [ ]:
df.info(5)

df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

(891, 12)

In [ ]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.isna().sum()*100/len(df)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.drop('Cabin',inplace=True,axis=1)

In [ ]:
#changing my ticket column to str as  i made an error in converting to numeric first
df['Ticket'] = df['Ticket'].astype(str)

#using regex
df['Ticket'] = df['Ticket'].str.replace(r'\D', '', regex=True)

df['Ticket'] = pd.to_numeric(df['Ticket'], errors='coerce')

df['Ticket'] = df['Ticket'].astype('Int64')

print(df['Ticket'].head())

0      5211710000
1       175990000
2    231012820000
3      1138030000
4      3734500000
Name: Ticket, dtype: Int64

In [ ]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,5211710.0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,175990.0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,231012820.0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,1138030.0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,3734500.0,8.0500,S

In [ ]:
#filling up age's missing values with its mean
df['Age'] = df['Age'].fillna(df['Age'].mean())
print("Succesfully filled up Age with mean")

Succesfully filled up Age with mean

/tmp/ipykernel_12890/3275549877.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Age'] = df['Age'].fillna(df['Age'].mean())

In [ ]:
df['Embarked']= df['Embarked'].fillna(df['Embarked'].mode())
print("Succesfully completed the 'Embarked' Column")

Succesfully completed the 'Embarked' Column

In [50]:
survivors=len(df[df['Survived']==1])*100/len(df)
victim=len(df[df['Survived']==0])*100/len(df)

print(f'Percentage of passengers who survived:', survivors)
print(f'Percentage of passengers who did not survive:', victim)

Percentage of passengers who survived: 38.38383838383838
Percentage of passengers who did not survive: 61.61616161616162